### ISSUE TITLE
Trace and Optimize breaks nHaruka's GrabFullBody

### ISSUE THREAD

**Issue by bdunderscore** [anatawa12/AvatarOptimizer#1155] opened 2024-08-24 02:13 UTC
https://nharuka.booth.pm/items/3905777

Enabling trace and optimize breaks this asset (grabbing the physbones it installs has no effect). Disabling "Remove unused Objects Automatically" is sufficient to avoid the issue.

**Comment by anatawa12** [comment] 2024-08-24 02:29
Duplicate of #1152 and fixed in #1153

**Closed by anatawa12** 2024-08-24 02:29 UTC
