### ISSUE TITLE
Optimize animations by disabling affected non-humanoid bones, PhysBones and colliders

### ISSUE THREAD

**Issue by GotoFinal** [anatawa12/AvatarOptimizer#1293] opened 2024-10-24 14:57 UTC
Currently if you create a toggle (manually, or using some tools or MA itself) for single piece of clothing (like just a skirt from a larger set) that requires PhysBones etc, they will all remain active - with many toggles this can add up to a lot of always active bones and colliders that do nothing.
It should be possible to find all the bones affected by the disabled/enabled mesh and if they are only used by this mesh, then disable them too. Currently it is possible to do this manually using MA Object Toggle, but having it happen automatically would improve performance of many avatars.

![image](https://github.com/user-attachments/assets/f0933a39-0ad6-4fd2-bed6-4a02a524ba75)
![image](https://github.com/user-attachments/assets/8c7c63ef-29d2-45e4-8e17-c60d26292886)

GPT 4: 現在、単一の衣装（例えば、大きなセットからスカートだけ）に対してトグルを作成すると（手動でも、ツールやMA自体を使用しても）、それに必要なPhysBonesなどがすべてアクティブなままになります。多くのトグルを作成すると、機能していないにもかかわらず常にアクティブなボーンやコライダーが大量に増えてしまう可能性があります。

無効化された、または有効化されたメッシュに影響するすべてのボーンを見つけ、それらがそのメッシュにのみ使用されている場合、ボーンも無効化することができるはずです。現在、この作業はMA Object Toggleを使用して手動で行うことが可能ですが、自動で行われれば、多くのアバターのパフォーマンスが向上するでしょう。

**Comment by anatawa12** [comment] 2024-10-25 02:15
Automatically toggling PhysBone is very requesting feature and tracked in #481. and partially implemented in #640 and released in 1.6.0.
You can see video demonstrates this optimization in this note: https://misskey.niri.la/notes/9mkhf0kygl.

The limitation for #640 is one PhysBone must affect only one (set) of meshes.
This is because we simply can copy active / disable animation of the (set) of meshes to PhysBone to implement the optimization.

It's unsupported to toggle PhysBones affecting multiple cloths that can be activated / disabled indivisually because it requires complex animation and I don't have enough time to do that.
I think we can use some codes of MA Reactive Components to implement the better optimization, but MA is planned to implement better animation generation in the near future so If I copy their implementation, I'll do after reimplementation in MA.

**Comment by anatawa12** [comment] 2024-10-25 02:16
I want to track one feature in one issue so I'm closing this issue as duplicate. If you have some ideas about this feature, Please comment in #481.

Duplicate of #481.

**Comment by anatawa12** [comment] 2024-10-25 02:16
Duplicate of https://github.com/anatawa12/AvatarOptimizer/issues/481.

**Closed by anatawa12** 2024-10-25 02:16 UTC

**Comment by anatawa12** [comment] 2024-10-25 13:38
P.S.

If you think your case is simple case I said above but not toggled correctly, It might be a bug so please create another bug report issue OR create discussion for investigation.
